= Compiler et construire ses applications avec maven
v1, 2022-02-20 : Initial draft
:icons: font
:diagrams: .
:experimental:
:imagesdir: images

// Specific to GitHub
ifdef::env-github[]
:toc:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:icongit: Git
endif::[]

//---------------------------------------------------------------

Ce TP vise à être capable de compiler un fichier Java sans être dépendant de son IDE favori.
Cela permet :

- d'être indépendant de tout IDE
- de faire construire l'application de manière automatique (c'est pour plus tard, mais c'est ce qu'on appelle l'intégration continue)

== Compiler et construire ses applications avec Maven

## Introduction
Ce TP vise à être capable de compiler un fichier Java sans être dépendant de son IDE favori. Cela permet :
- d’être indépendant de tout IDE
- de faire construire l’application de manière automatique (c’est pour plus tard, mais c’est ce qu’on appelle l’intégration continue)

## Mise en place
Les illustrations utilisent VS Code, mais peu importe que vous utilisiez un autre IDE comme Eclipse ou IntelliJ, il vous suffit d’adapter à votre IDE (qu’il vous faut apprendre à connaître).


== *Compilation*

1. Tout d'abord créez un repertoire local pour votre projet.

----
mkdir $HOME/Documents/tp_qualite
----

2. Ensuite y accedez. (Je ne sais pas pourquoi ça m'affiche 1 au lieu de 2)

----
cd $HOME/Documents/tp_qualite
----

3. Il faut ensuite faire un clone du repo concerné dans votre machine.

----
git clone https://github.com/IUT-Blagnac/r2-03-td4-maven-2024-MeteIsCoding.git
----

4. Compilez le projet en utilisant Maven :

----
mvn compile
----

== *Creation d'executable*

Maintenant on va creer la version executable de votre projet.

----
mvn package
----

Observez la création du fichier JAR et testez-le :

----
java -jar target/tp_qualite-1.0.jar
----